apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: storage-dashboard
  annotations:
    description: "Storage Integration Dashboard for OpenShift Virtualization"

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - route.yaml

commonLabels:
  app: storage-dashboard
  version: v1.0.0

namespace: storage-dashboard

images:
  - name: storage-dashboard
    newTag: latest