apiVersion: v1
kind: Service
metadata:
  name: storage-dashboard
  labels:
    app: storage-dashboard
    component: web
spec:
  selector:
    app: storage-dashboard
    component: web
  ports:
  - name: web
    port: 80
    targetPort: 3001
    protocol: TCP
  type: ClusterIP